### PR TITLE
Add tracks to about section

### PR DESCRIPTION
**Pull request by lucca**
## PR Description and Purpose

Adds tracks to the website.

## Related Issues (if any)

Fixes #

## Miscellaneous

- [x] I have read the contributing guidelines
- [x] I abide by this repository Code of Conduct

Do you want to add anything else? We :heart: to hear your opinions!
awefaweffawefefawefeawefawefawefefawefefaweff

### CODE REVIEW

**Comment by peasant98** [comment]
arrived before netlify preview lol

**Review by peasant98 — COMMENTED** [review]
maybe some space after the tracks window and between the our story windows?

**Comment by lucca** [comment]
> maybe some space after the tracks window and between the our story windows?

The spacing is done through sections, but I didn't really want to make it into its own section, so there's some kind of weird css that I did to fix it. We can also just make the tracks its own section if you want but we'd need to add another button and idk if it would fit lol

**Comment by peasant98** [comment]
alright lgtm

**Pull request merged**
