### PR TITLE
Updates from event

### PR DESCRIPTION
**Pull request by AparaV**
## What this PR does / why we need it
Updates the website with event statistics; removes apply buttons, etc.

## Some questions
- [x] I have read the contributing guidelines
- [x] I abide by this repository Code of Conduct

## Special notes for your reviewer

@casassg can I get some statistics from the backend that I can here - like gender ratio, hacker map, etc.?

### CODE REVIEW

**Review by casassg — CHANGES_REQUESTED** [review]
is this ready? There's no stats!

**Comment by AparaV** [comment]
I added some stats that I could get from the admin dashboard. Is there more that I missed?
Also, can we embed the map you created - [the map](https://casassg.carto.com/builder/ba982832-ebd7-470a-b0d3-357203c83630/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B-67.63599365800934%2C-246.16404533386233%5D%2C%22sw%22%3A%5B82.93167840138106%2C268.52345466613775%5D%2C%22center%22%3A%5B31.593498925980057%2C11.179704666137697%5D%2C%22zoom%22%3A2%7D%7D)?

**Comment by casassg** [comment]
Yes, go for it 😄

**Review by casassg — APPROVED** [review]

**Comment by casassg** [comment]
screencapture-localhost-4000-2018-03-13-07_51_40

**Pull request merged**
