### PR TITLE
Add github as sponsor

### LINKED ISSUE #45: Add GitHub Logo to Sponsor Page
GitHub will be sponsoring at our Bronze tier. Let's add their logo to our sponsor page.

github_logo

### PR DESCRIPTION
**Pull request by casassg**
## What this PR does / why we need it

@elliotwhitehead  confirmed GitHub as a bronze sponsor. Adding them on the website.
## Related Issues

Fixes #45 

## Some questions

- [x] I have read the contributing guidelines
- [x] I abide by this repository Code of Conduct

### CODE REVIEW

**Comment by elliotwhitehead** [comment]
:shipit:

**Review by elliotwhitehead — COMMENTED** [review]
:shipit:

**Comment by casassg** [comment]
Nop... Approve!

**Review by elliotwhitehead — APPROVED** [review]
LGTM

**Comment by casassg** [comment]
Thanks!

**Pull request merged**
